---
title: "Ray Chen"
author: "Ray Chen"
date: "4/10/2021"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Libraries, include=FALSE}
library(tidyverse)
library(ggplot2)
library(lme4)
library(gamm4)
library(lmtest)
```

```{r}
# Data
black_saber_current_employees <- read.csv("data/black-saber-current-employees.csv")
final_hires_newgrad_2020 <- read.csv("data/final-hires-newgrad_2020.csv")
phase_1 <- read.csv("data/phase1-new-grad-applicants-2020.csv")
phase_2 <- read.csv("data/phase2-new-grad-applicants-2020.csv")
phase_3 <- read.csv("data/phase3-new-grad-applicants-2020.csv")
```



```{r}
# each employee serve different number of years at the company
employee_clean <- black_saber_current_employees %>% 
  group_by(employee_id) 


# Summarize promotion data for each employee
promotion_stat <- employee_clean %>% 
  group_by(employee_id ,role_seniority) %>% 
  summarise(count = n(), .groups = 'drop') %>% 
  group_by(employee_id) %>% 
  mutate(quarter_of_service= sum(count)) 


# number of times each employee get promoted 
n_promotion <- promotion_stat %>% 
  group_by(employee_id) %>% 
  count(role_seniority) %>% 
  summarise(n_promotion = n() -1 , .groups = 'drop') 



# join promotion number and quarter_of_service together 
promotion_rate <-  full_join(n_promotion, promotion_stat, by = "employee_id") %>% 
  mutate(rate = n_promotion/quarter_of_service) %>% 
  arrange(-rate)

# promoted employees and their promotion rate by quarter
subset <- promotion_rate %>% 
  select(employee_id, rate, n_promotion) %>% 
  distinct()


# Define promotion rate and add to the employee dataset
fully_clean <- left_join(employee_clean, subset, by = "employee_id")

```




```{r}
# Define dummy variable and specify each quarter's promotion status
testing <- employee_clean %>% 
  group_by(employee_id) %>% 
  mutate(x = lag(role_seniority)) %>% 
  mutate(promoted = ifelse(role_seniority != x, 1,0)) %>% 
  mutate(promoted = ifelse(is.na(promoted), 0, promoted)) %>% 
  mutate(team = as_factor(team)) %>% 
  mutate(leadership_for_level =fct_relevel(leadership_for_level))


# data for promotion count link to each person's employee data
dat_new <- full_join(n_promotion, employee_clean, by = "employee_id") 


```

```{r}
# male vs female ratio
testing %>% 
  group_by(gender) %>% 
  summarise(count = n(), .groups = 'drop') %>% 
  mutate(gender_ratio = count/sum(count))

# data exploration on the number of promotions happened within the company 
testing %>% 
  mutate(promoted = case_when(
    promoted == 1 ~ "promoted",
    promoted == 0 ~ "not promoted"
  )) %>% 
  group_by(promoted, gender) %>% 
  summarise(number_of_promotions = n(), .groups = 'drop') %>% 
  group_by(promoted) %>% 
  mutate(ratio = number_of_promotions/ sum(number_of_promotions))
  

# data exploration on promoted employees
testing %>% 
  mutate(promoted = case_when(
    promoted == 1 ~ "promoted",
    promoted == 0 ~ "not promoted"
  )) %>% 
  filter(promoted == "promoted") %>% 
  ggplot(aes(x = promoted, colour = gender, fill = gender)) + 
  geom_bar(position = "dodge") + 
  theme_minimal() +
  scale_y_continuous(breaks = seq(0, 400, 50))

# # data exploration on number of promotion by gender 
# fully_clean %>% 
#   ggplot(aes(x = gender, y = n_promotion)) + 
#   geom_boxplot() + 
#   theme_minimal()

```




# Fitting the model
```{r}
#  model with only fixed effects 
model_1 <- glm(promoted ~ productivity + gender + leadership_for_level, data = testing, family = binomial(link = "logit"))
summary(model_1)
confint(model_1)

# glmm with all random effects on team and team:employee_id
model_4 <- glmer(promoted~ productivity + gender + leadership_for_level + (1|team) + (1|team:employee_id), nAGQ = 0, family = binomial, data = testing)
summary(model_4)
confint(model_4)

# likelihood ratio test between the two models to help with model selection
lrtest(model_1, model_4)
```



