---
title: "Stella Bae"
author: "Stella Bae"
date: "4/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lme4)

knitr::opts_chunk$set(echo = FALSE)
```

```{r read data}

black_saber_current_employees <- read_csv("data/black-saber-current-employees.csv")

```

```{r data wrangling}


black_saber_current_employees <- black_saber_current_employees %>% 
  mutate(
    salary = as.numeric(gsub('[$,]', '', salary))
  ) %>% 
  mutate(gender = ifelse(gender == "Man", 1, 0))

# Relevel the roles in ascending order
black_saber_current_employees$role_seniority = fct_relevel(
    black_saber_current_employees$role_seniority,
    "Entry-level",
    "Junior I",
    "Junior II",
    "Senior I",
    "Senior II",
    "Senior III",
    "Manager",
    "Director",
    "Vice president"
  )

black_saber_current_employees$leadership_for_level = fct_relevel(
  black_saber_current_employees$leadership_for_level,
  "Appropriate for level",
  "Needs improvement",
  "Exceeds expectations"
)
```

```{r model}

model1 <- lmer(salary ~ gender + role_seniority + leadership_for_level + productivity + (1|team), data = black_saber_current_employees)

summary(model1)
confint(model1)

model2 <- glm(salary ~ gender + role_seniority + leadership_for_level + productivity, data = black_saber_current_employees)

summary(model2)

```